export const teamMembers = [
  {
    name: "Christopher Lai",
    title: "Full Stack Developer",
    description: "Focuses on user experience and design.",
    email: "clai20707@gmail.com",
    github: "chrislies",
    linkedin: "christwofour",
    bio: "Christopher is our lead UI/UX designer. With a keen eye for design and user experience, he ensures all interfaces are intuitive and engaging.",
  },
  {
    name: "Jiaxin Lin",
    title: "Backend Developer",
    description: "Expert in Node.js and databases.",
    email: "jiaxinlin200204@gmail.com",
    github: "Shion1314",
    linkedin: "jiaxinl1314",
    bio: "Jiaxin is a backend specialist with extensive experience in server-side languages and database management. He ensures our data systems are efficient and secure.",
  },
  {
    name: "Xuanrong Hong",
    title: "Backend Developer",
    description: "Guarantees product quality and reliability.",
    email: "hxr3136754148@gmail.com",
    github: "Xhong0921-rong",
    linkedin: "xuanrong-hong-157b82240",
    bio: "Xuanrong oversees our quality assurance processes, implementing rigorous testing methods to ensure our application meets high standards.",
  },
  {
    name: "Eric Ma",
    title: "Frontend Developer",
    description: "Specializes in React and CSS.",
    email: "ericma25.em@gmail.com",
    github: "em-cp",
    linkedin: "",
    bio: "Eric has over 10 years of experience in front-end technologies including React, Angular, and Vue.js. He is passionate about building accessible, user-friendly web applications.",
  },
];
